### ISSUE TITLE
Combat mode triggered even when not standing inside blocks

### ISSUE THREAD

**Issue by appgurueu** [MT-CTF/capturetheflag#931]
The check doesn't take different collisionboxes of slabs, stairs etc. into account at all. A proper implementation like https://github.com/appgurueu/modlib/blob/master/minetest/collisionboxes.lua must be used instead.

Note that the `else` branch will happily push combat time higher and higher while you're standing on slabs: https://github.com/MT-CTF/capturetheflag/blob/master/mods/ctf/ctf_combat/ctf_combat_mode/init.lua#L35

**Comment by savilli** [comment]
FIxed in 746c5c3bfd15ee530721b82feb4bcb854bc6633e

**Comment by appgurueu** [comment]
> FIxed in [746c5c3](https://github.com/MT-CTF/capturetheflag/commit/746c5c3bfd15ee530721b82feb4bcb854bc6633e)

No, not fixed, rather hacked around (and only applying to water?).

The timer should still trigger if you're inside stairs/slabs, meaning there's no way around using collisionboxes for a clean solution.

**Comment by savilli** [comment]
Looks good to me
